/**
 * Lookup for the responsive derivatives generated by
 * backend/scripts/backfill-image-variants.js.
 *
 * The manifest is keyed by the ORIGINAL image URL, which is the only thing the
 * pages know about:
 *
 *   "https://geniestudio.in/uploads/1786…-962658427.jpg": {
 *     width, height, lqip,
 *     variants: { webp: { 400: url, … }, avif: { 400: url, … } }
 *   }
 *
 * Shipping this as static data rather than fetching it means a hardcoded <img>
 * gets its srcSet with no extra request and no waiting on Render — which
 * matters because Render's free tier cold-starts, and images should never be
 * blocked behind an API call.
 *
 * Images uploaded after the last backfill are not in here; they carry their own
 * `variants` on the API row instead, and OptimizedImage prefers those.
 */

import manifest from "./imageManifest.json";

/**
 * Hostinger serves the same file under a few spellings that appear in the DB
 * (protocol-relative, http, occasional trailing query). Normalising here keeps
 * one canonical key instead of storing every variation.
 */
function canonical(url) {
  if (typeof url !== "string" || url === "") return "";
  return url
    .replace(/^http:\/\//i, "https://")
    .replace(/^\/\//, "https://")
    .split("?")[0]
    .trim();
}

/**
 * @param {string} src original image URL
 * @returns {{width?:number, height?:number, lqip?:string, variants?:object}|null}
 */
export function lookupImage(src) {
  if (!src) return null;
  return manifest[canonical(src)] || null;
}

/**
 * The single best URL at or above a target width — used where a real <picture>
 * is impossible, notably CSS `background-image` heroes.
 *
 * Prefers WebP over AVIF here on purpose: this URL gets used without any
 * content negotiation or type hint, and WebP support is effectively universal
 * while a browser that cannot decode AVIF would render nothing at all.
 */
export function bestVariantUrl(src, targetWidth = 1600) {
  const entry = lookupImage(src);
  const byWidth = entry?.variants?.webp;
  if (!byWidth) return src;

  const widths = Object.keys(byWidth)
    .map(Number)
    .filter(Number.isFinite)
    .sort((a, b) => a - b);
  if (widths.length === 0) return src;

  const chosen = widths.find((w) => w >= targetWidth) ?? widths[widths.length - 1];
  return byWidth[chosen] || src;
}

export default manifest;
